config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'
  get    :about,         to: 'static_pages#about'
  get    :use_of_terms,  to: 'static_pages#terms'
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  get    :recruit_login, to: 'sessions#new2'
  get    :favorites,     to: 'favorites#index'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :drinks
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  post   "favorites/:drink_id/create"  => "favorites#create"
  delete "favorites/:drink_id/destroy" => "favorites#destroy"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "House Coffeeとは？") %>
<aside id="fh5co-hero" class="js-fullheight" style="height:697px;">
  <div class="flexslider js-fullheight" style="height:697px;">
    <ul class="slides">
      <div class="overlay"></div>
      <div class="container">
        <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text animated fadeInUp" style="height:697px;">
          <div class="slider-text-inner">
            <h1>House Coffeeとは？</h1>
            <br>
            <h4>毎日飲むお気に入りのコーヒーレシピをシェアできるサービスです。</h4>
            <br>
            <h3>＊ 使い方 ＊</h3>
            <br>
            <p>　　いつも作っているコーヒーのレシピをシェアしてみましょう！</p>
            <p>　　リモートワークが進み、家で飲むことが多くなったコーヒー。</p>
            <p>　　本格的なドリップコーヒーの淹れ方、話題のコーヒーをシェアしたり、</p>
            <p>　　みんなのオリジナルコーヒーを家で試してみよう！</p>
          </div>
        </div>
      </div>
    </ul>
  </div>
</aside>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3>みんなのコーヒー (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しいコーヒーをシェアする", new_drink_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "コーヒーレシピ一覧をCSV出力", drinks_path(format: :csv), class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
  <aside id="fh5co-hero" class="js-fullheight" style="height:697px;">
    <div class="flexslider js-fullheight" style="height:697px;">
      <ul class="slides">
      <div class="overlay"></div>
      <div class="container">
        <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text animated fadeInUp" style="height:697px;">
          <div class="slider-text-inner">
            <h1>最高の一杯のコーヒーを<br>あなたの自宅で。</h1>
            <p>お気に入りのコーヒーをシェアしよう！</p>
            <p><%= link_to "さっそく始める！", login_path,  class: "btn btn-primary btn-lg" %></p>
            <p><%= link_to "簡単ログイン", recruit_login_path,  class: "btn btn-primary btn-lg" %></p>
          </div>
        </div>
      </ul>
    </div>
  </aside>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<aside id="fh5co-hero" class="js-fullheight" style="height:697px;">
  <div class="flexslider js-fullheight" style="height:697px;">
    <ul class="slides">
    <div class="overlay"></div>
    <div class="container">
      <div class="col-md-10 col-md-offset-1 text-center js-fullheight slider-text animated fadeInUp" style="height:697px;">
        <div class="slider-text-inner">
          <h1>利用規約</h1>
        </div>
      </div>
    </ul>
  </div>
</aside>