config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'
  get    :about,         to: 'static_pages#about'
  get    :use_of_terms,  to: 'static_pages#terms'
  get    :signup,        to: 'users#new'
  get    :login,         to: 'sessions#new'
  get    :recruit_login, to: 'sessions#new2'
  get    :favorites,     to: 'favorites#index'
  post   :login,         to: 'sessions#create'
  delete :logout,        to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :drinks
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  post   "favorites/:drink_id/create"  => "favorites#create"
  delete "favorites/:drink_id/destroy" => "favorites#destroy"
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="お気に入りのコーヒーやコーヒー豆、コーヒーの淹れ方など投稿できるようなSNSです。" />
<meta name="keywords" content="House Coffee, コーヒー, レシピ, SNS" />
<link rel="shortcut icon" href="/images/favicon.ico">

<!-- Facebook and Twitter integration -->
<meta property="og:title" content=""/>
<meta property="og:image" content=""/>
<meta property="og:url" content=""/>
<meta property="og:site_name" content=""/>
<meta property="og:description" content=""/>
<meta name="twitter:title" content="" />
<meta name="twitter:image" content="" />
<meta name="twitter:url" content="" />
<meta name="twitter:card" content="" />

<link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">

<%= stylesheet_link_tag    'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 House Coffee All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id ="fh5co-header">
  <header class="fh5co-header-section">
    <div class="container">
      <div class="nav-header">
        <div id="top-logo">
          <%= link_to(image_tag("/images/house_coffee.png", :alt => "house_coffeeのロゴ写真"), root_url, id: 'logo') %>
        </div>
        <nav id="fh5co-menu-wrap">
          <ul class="nav-header sf-menu a">
            <li><%= link_to about_path do %><span class="fas fa-check"></span> <span>House Coffeeとは？</span><% end %></li>
            <% if logged_in? %>
              <% if current_user.notification == true %>
                <li class="new_notification header-link">
              <% else %>
                <li class="no_notification header-link">
              <% end %>
              <%= link_to notifications_path do %><span class="fas fa-bell"> <span>通知</span><% end %>
              </li>
              <li><%= link_to favorites_path do %><span class="fas fa-heart"></span> <span>お気に入り</span><% end %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fas fa-user">
                  My Page <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'プロフィール', current_user %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'ユーザー', users_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                  <li class="divider"></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to signup_path do %><span class="fas fa-user-plus"></span> <span>ユーザー登録(無料)</span><% end %></li>
              <li><%= link_to login_path do %><span class="fas fa-home"></span> <span>ログイン</span><% end %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
</div>

app/views/layouts/_js.html.erb
<!-- jQuery -->
<%= javascript_include_tag('superfish') %>
<!-- jQuery -->
<%= javascript_include_tag('jquery.stellar.min') %>
<!-- jQuery -->
<%= javascript_include_tag('jquery.countTo') %>
<!-- jQuery -->
<%= javascript_include_tag('jquery.min') %>
<!-- jQuery Easing -->
<%= javascript_include_tag('jquery.easing.1.3') %>
<!-- Bootstrap -->
<%= javascript_include_tag('bootstrap.min') %>
<!-- Waypoints -->
<%= javascript_include_tag('jquery.waypoints.min') %>
<!-- Flexslider -->
<%= javascript_include_tag('jquery.flexslider-min') %>
<!-- Main -->
<%= javascript_include_tag('main') %>
<!-- google -->
<%= javascript_include_tag('google_map') %>
<!-- Custom -->
<%= javascript_include_tag('custom') %>

app/views/layouts/_search.html.erb
<div class="row">
  <%= search_form_for @q do |f| %>
    <div class="col-md-10">
      <div class='form-group'>
        <%= f.search_field :name_or_items_name_cont, placeholder: "コーヒー名、必要なモノで検索", class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class='form-group'>
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="js/respond.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="fh5co-wrapper">
      <div id="fh5co-page">
        <div id="demo-main">
          <%= render 'layouts/header' %>
          <div class="body-page">
            <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
            <%= render 'layouts/search' if logged_in? %>
            <%= yield %>
          </div>
        </div>
        <%= render 'layouts/footer' %>
      </div>
    </div>
    <%= render 'layouts/js' %>
  </body>
</html>